spring.application.name=demoweb2

spring.datasource.hikari.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.jdbc-url=jdbc:mysql://localhost:3306/demoweb3?serverTimezone=Asia/Seoul
spring.datasource.hikari.username=root
spring.datasource.hikari.password=mysql
spring.datasource.hikari.connection-test-query=SELECT 1

spring.jpa.database=mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.hibernate.use-new-id-generator-mappings=false
spring.jpa.show-sql=true

mybatis.configuration.map-underscore-to-camel-case=true
mybatis.type-aliases-package=com.humanda6.demoweb2.dto

spring.main.allow-bean-definition-overriding=true

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=120MB

# settings for spring security config 1-1
#spring.security.user.name=iamuserone
#spring.security.user.password=iamuserone
